### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by meghalithic** [meghalithic/DeepBryo_micro#1]
- [x] figure out padding to exclude zooids not completely in the image
`python app/app-cli.py -i ~/Desktop/microporella-jpg/IMAGE -o ~/Documents/GitHub/bryozoa/DeepBryo_micro -p [left, top, right, bottom]`
- [x] figure out scaling 
`python app/app-cli.py -i ~/Desktop/microporella-jpg/IMAGE -o ~/Documents/GitHub/bryozoa/DeepBryo_micro -sc SCALE`

**Comment by meghalithic** [comment]
- [x] make an issue with images with a black scale bar and those without
  - [x] put list of these images somewhere
- [x] check using app (browser) if rotation affects how well DeepBryo identifies zooids
- [x] put list of images that are not x50
- [x] take screenshot of output of using scrictness and autofiltering

**Comment by lilysandstrom** [comment]
![Screenshot from 2024-06-25 16-32-17](https://github.com/meghalithic/DeepBryo_micro/assets/117290965/79152969-1df8-4924-bfbb-2d353aea52e0)
![Screenshot from 2024-06-25 16-40-45](https://github.com/meghalithic/DeepBryo_micro/assets/117290965/0d9a5dff-8a0d-4dcd-a79e-ecd37e02f035)

I've been trying to add the optional command padding in the command line, but getting error messages; mostly either:
app-cli.py: error: argument -p/--padding: invalid float value
or
app-cli.py: error: unrecognized arguments

**Comment by lilysandstrom** [comment]
Images that have a 118 pixel wide black boarder at the bottom where the scale bare is:
MHR.4325 - MHR.8794. Of these, all are x50 magnificaction, except 11 images, which are:
MHR.4625 (x40)
MHR.4626 (x40)
MHR.4827 (x60)
MHR.5026 (x30)
MHR.6751 (x40)
MHR.6752 (x40)
MHR.7197 (x40)
MHR.7198 (x40)
MHR.8541 (x60)
MHR.8542 (x60)
MHR.8543 (x60)
(MHR.8679 is flipped upside down but is x50)

**Comment by lilysandstrom** [comment]
Images that have no black scale-bar boarder are MHR.8805 - MHR.12836.
All of these are x50.
MHR.8994 and MHR.12257 are flipped 90 degrees counter-clockwise.

**Comment by lilysandstrom** [comment]
All the x50 seem to have a scale/conversion factor of 1.00864 pixels per micrometer. Edit: yes, you're right! The scale bar is 1.00 mm (which is not 100 micrometers, but 1000 micrometers)!

**Comment by meghalithic** [comment]
> I've been trying to add the optional command padding in the command line, but getting error messages; mostly either: app-cli.py: error: argument -p/--padding: invalid float value or app-cli.py: error: unrecognized arguments

I messaged Arthur about this

**Comment by meghalithic** [comment]
> All the x50 seem to have a scale/conversion factor of 10.0864 pixels per micrometer.

Is it not 1.009?

**Comment by meghalithic** [comment]
> Images that have no black scale-bar boarder are MHR.8805 - MHR.12836. All of these are x50. MHR.8994 and MHR.12257 are flipped 90 degrees counter-clockwise.

Can you show me an example?

**Comment by lilysandstrom** [comment]
![Screenshot from 2024-06-26 11-13-39](https://github.com/meghalithic/DeepBryo_micro/assets/117290965/4e4858d4-c929-4fe1-961e-a2abd70b1dd9)
Output with no autofiltering: 
I have not turned on the autofilter gradient boosting algorithm here. In image MHR.4625 for example, only a few autozooids seemed useable (so I would remove all others from the csv output). It seems that DeepBryro has not detected any ascopores even though some ascopores are visible to me in the jpg. I can try to play around with the confidence and the autofiltering settings to try to get it to detect the ascopores. Of the useable autozooids that DeepBryo seems to have detected well, I can see for example that the avicularial area marked 22 is a bit overestimated. The area for autozooid 2 also seems to be off, and it has not detected the orifice. I'll move on to the other images for now. It may be that images like this should just be discarded, but some data could potentially be extracted.

**Comment by lilysandstrom** [comment]
Note to self: try -p and numbers, without brackets or commas, only spaces.

**Comment by lilysandstrom** [comment]
Padding works when input is whole numbers separated by spaces only, without brackets, parentheses, or commas. 
Eg. -p 5 5 5 5
There were however multiple user warnings. They may be irrelevant, but could also be an issue when processing a larger set of images.
![Userwarnings-padding-command](https://github.com/meghalithic/DeepBryo_micro/assets/117290965/85130685-8ec6-453b-b73e-1520c03b9e34)

**Comment by lilysandstrom** [comment]
- [ ] Find a way to search for class without opesia and spiramen because none of the species should have them.
- [ ] Check if there are systematic differences in DeepBryos output between the species
- [ ] Find out how to select which objects to keep rather than which to remove, or add "select all" option.
- [ ] Find out if it's possible to open an image folder in the webapp, and press next to go through manually

Padding: for images MHR4325 - MHR.8794 with 118 pixel wide black boarder, padding can be 5 5 5 125 for example.
Padding for images MHR.8805 - MHR.12836 can be 5 5 5 5
